(ns hive-schemas.emit
  "Render verification plans into source.

   Pure except `spit-ns!`.

   Levers:
     unprintable   form -> the leaves that cannot round-trip through the reader
     plan->form    Plan -> the deftriad-from-schema form that synthesizes it
     plans->forms  [Plan] -> [form]
     ns-form       an emission spec -> its (ns ...) form
     render-ns     an emission spec -> deterministic source text
     ns->path      ns symbol + extension -> the relative source path
     spit-ns!      root + an emission spec -> {:ok path} | {:error ...}"
  (:require [clojure.java.io :as io]
            [clojure.pprint :as pprint]
            [clojure.string :as str]
            [hive-schemas.plan :as plan]
            [hive-schemas.vocab :as vocab]
            [malli.core :as m]))

;; SPDX-License-Identifier: MIT
;; Copyright (C) 2026 Pedro Gomes Branquinho (BuddhiLW) <pedrogbranquinho@gmail.com>

(def ^:private synthesis-macro
  "The macro a rendered plan expands through, in the consumer's namespace."
  'hive-schemas.test/deftriad-from-schema)

;; =============================================================================
;; Printability
;; =============================================================================

(defn unprintable
  "The leaves of `form` that cannot be read back — function objects, atoms,
   regexes and other opaque values.

   A `:rel` given as a compiled `(fn [in out] ...)` lands here: emission needs a
   symbol or a form."
  [form]
  (into []
        (remove (fn [x]
                  (or (nil? x) (symbol? x) (keyword? x) (string? x)
                      (number? x) (boolean? x) (char? x) (coll? x))))
        (tree-seq coll? seq form)))

;; =============================================================================
;; Plan -> form
;; =============================================================================

(defn plan->form
  "The `deftriad-from-schema` form that synthesizes `p`.

   Throws `:emit/invalid-plan` when `p` does not conform to :hive.schemas/plan,
   `:emit/unprintable` when its options carry a value that cannot be rendered as
   source."
  [p]
  (when-let [problem (plan/explain p)]
    (throw (ex-info "Plan does not conform to :hive.schemas/plan"
                    {:error :emit/invalid-plan
                     :explanation (:errors problem)
                     :plan p})))
  (let [opts (plan/plan->opts p)
        bad  (unprintable opts)]
    (when (seq bad)
      (throw (ex-info "Plan options carry values that cannot be rendered as source"
                      {:error :emit/unprintable
                       :plan (:plan/name p)
                       :unprintable (mapv str bad)})))
    (list synthesis-macro (:plan/name p) (:plan/subject p) opts)))

(defn plans->forms
  "The synthesis forms for `plans`, in order."
  [plans]
  (mapv plan->form plans))

;; =============================================================================
;; Namespace rendering
;; =============================================================================

(defn- subject-namespaces
  "Namespaces the subjects of `plans` live in, sorted and deduplicated."
  [plans]
  (->> plans
       (keep (comp namespace :plan/subject))
       (map symbol)
       distinct
       sort
       vec))

(defn ns-form
  "The `(ns ...)` form for an emission spec `{:ns :plans :requires :doc}`.

   Requires are the union of `:requires`, the subjects' own namespaces, and
   `hive-schemas.test`."
  [{:keys [ns plans requires doc]}]
  (let [required (->> (concat ['hive-schemas.test] (subject-namespaces plans) requires)
                      (map #(if (vector? %) % [%]))
                      (distinct)
                      (sort-by (comp str first))
                      vec)]
    (list* 'ns ns
           (concat (when doc [doc])
                   [(list* :require required)]))))

(def ^:private banner
  ";; GENERATED by hive-schemas.emit from verification plans. Edit the plans,\n;; not this file.\n")

(defn render-ns
  "Deterministic source text for an emission spec
   `{:ns :plans :requires :doc :preamble}`. The same spec renders the same bytes.

   `:preamble` forms are rendered after the ns form and before the plans, for
   the setup a generated suite needs before its subjects resolve."
  [{:keys [plans preamble] :as spec}]
  (binding [*print-length*         nil
            *print-level*          nil
            *print-namespace-maps* false
            *print-meta*           false]
    (let [render (fn [form] (str/trim-newline (with-out-str (pprint/pprint form))))
          blocks (concat (map render preamble)
                         (map render (plans->forms plans)))]
      (str (render (ns-form spec)) "\n\n"
           banner
           (str/join "\n\n" blocks)
           "\n"))))

(defn ns->path
  "Relative source path for `ns-sym`, e.g. `a.b-c` + \"cljc\" -> \"a/b_c.cljc\"."
  ([ns-sym] (ns->path ns-sym "clj"))
  ([ns-sym extension]
   (str (-> (str ns-sym) (str/replace "-" "_") (str/replace "." "/"))
        "." extension)))

;; =============================================================================
;; Boundary
;; =============================================================================

(defn spit-ns!
  "Write `spec`'s rendered source under `root`.

   Refuses an existing file unless `:overwrite? true`. Returns `{:ok path}` or
   `{:error :emit/exists :path path}`."
  [root {:keys [ns extension overwrite?] :or {extension "clj"} :as spec}]
  (let [file (io/file root (ns->path ns extension))
        path (str file)]
    (if (and (.exists file) (not overwrite?))
      {:error :emit/exists :path path}
      (do (.mkdirs (.getParentFile file))
          (spit file (render-ns spec))
          {:ok path}))))

;; =============================================================================
;; Contracts
;; =============================================================================

(m/=> unprintable [:=> [:cat :any] [:vector :any]])

(m/=> plan->form [:=> [:cat :any] [:sequential :any]])

(m/=> plans->forms [:=> [:cat [:maybe [:sequential :any]]] [:vector :any]])

(m/=> ns-form [:=> [:cat [:maybe [:map]]] [:sequential :any]])

(m/=> render-ns [:=> [:cat [:maybe [:map]]] :string])

(m/=> ns->path
      [:function
       [:=> [:cat :any] vocab/Path]
       [:=> [:cat :any vocab/Path] vocab/Path]])

(m/=> spit-ns! [:=> [:cat :any [:maybe [:map]]] [:map]])
